# Model(classes change according to dataset)
network: CSANet
network_args:
  classes: 2

# Data (use self processed data path)
data_path: /mnt/cxr/CSANet/2b
out_folder: /mnt/cxr/CSANet/output/2b

# Training
preferred_device: gpu
nGPU: 0
random_seed: 0

batch_size: 64

epochs: 2000

lr: 0.0009

# Data augmentation
num_classes: 2
num_segs: 8